#' GroupDashboardPCRAge
#'
#' @description Groupe PCR age categories in 0-19, 20-59 and 60-more
#'
#' @param df The dashboard dataframe
#'
#' @return A dataframe with the grouped categories
#' @export
GroupDashboardPCRAge <- function(df){
  result <- df %>%
    mutate(GRP_GIRONDE_P_0_19_ANS = GIRONDE_P_0_9_ANS + GIRONDE_P_10_19_ANS,
           GRP_GIRONDE_P_20_59_ANS = GIRONDE_P_20_29_ANS + GIRONDE_P_30_39_ANS + GIRONDE_P_40_49_ANS + GIRONDE_P_50_59_ANS,
           GRP_GIRONDE_P_60_90_PLUS_ANS = GIRONDE_P_60_69_ANS + GIRONDE_P_70_79_ANS + GIRONDE_P_80_89_ANS + GIRONDE_P_90_ANS_ET_PLUS,
           GRP_GIRONDE_P_TOUS_AGES = GIRONDE_P_TOUS_AGES,
           GRP_GIRONDE_TESTED_0_19_ANS = GIRONDE_TESTED_0_9_ANS + GIRONDE_TESTED_10_19_ANS,
           GRP_GIRONDE_TESTED_20_59_ANS = GIRONDE_TESTED_20_29_ANS + GIRONDE_TESTED_30_39_ANS + GIRONDE_TESTED_40_49_ANS + GIRONDE_TESTED_50_59_ANS,
           GRP_GIRONDE_TESTED_60_90_PLUS_ANS = GIRONDE_TESTED_60_69_ANS + GIRONDE_TESTED_70_79_ANS + GIRONDE_TESTED_80_89_ANS + GIRONDE_TESTED_90_ANS_ET_PLUS,
           GRP_GIRONDE_TESTED_TOUS_AGES = GIRONDE_TESTED_TOUS_AGES,
           GRP_GIRONDE_FRACP_0_19_ANS = GRP_GIRONDE_P_0_19_ANS/GRP_GIRONDE_TESTED_0_19_ANS,
           GRP_GIRONDE_FRACP_20_59_ANS = GRP_GIRONDE_P_20_59_ANS/GRP_GIRONDE_TESTED_20_59_ANS,
           GRP_GIRONDE_FRACP_60_90_PLUS_ANS = GRP_GIRONDE_P_60_90_PLUS_ANS/GRP_GIRONDE_TESTED_60_90_PLUS_ANS,
           GRP_GIRONDE_FRACP_TOUS_AGES = GIRONDE_FRACP_TOUS_AGES,

           GRP_CHU_P_0_19_ANS = CHU_P_0_9_ANS + CHU_P_10_19_ANS,
           GRP_CHU_P_20_59_ANS = CHU_P_20_29_ANS + CHU_P_30_39_ANS + CHU_P_40_49_ANS + CHU_P_50_59_ANS,
           GRP_CHU_P_60_90_PLUS_ANS = CHU_P_60_69_ANS + CHU_P_70_79_ANS + CHU_P_80_89_ANS + CHU_P_90_ANS_ET_PLUS,
           GRP_CHU_P_TOUS_AGES = CHU_P_TOUS_AGES,
           GRP_CHU_TESTED_0_19_ANS = CHU_TESTED_0_9_ANS + CHU_TESTED_10_19_ANS,
           GRP_CHU_TESTED_20_59_ANS = CHU_TESTED_20_29_ANS + CHU_TESTED_30_39_ANS + CHU_TESTED_40_49_ANS + CHU_TESTED_50_59_ANS,
           GRP_CHU_TESTED_60_90_PLUS_ANS = CHU_TESTED_60_69_ANS + CHU_TESTED_70_79_ANS + CHU_TESTED_80_89_ANS + CHU_TESTED_90_ANS_ET_PLUS,
           GRP_CHU_TESTED_TOUS_AGES = CHU_TESTED_TOUS_AGES,
           GRP_CHU_FRACP_0_19_ANS = GRP_CHU_P_0_19_ANS/GRP_CHU_TESTED_0_19_ANS,
           GRP_CHU_FRACP_20_59_ANS = GRP_CHU_P_20_59_ANS/GRP_CHU_TESTED_20_59_ANS,
           GRP_CHU_FRACP_60_90_PLUS_ANS = GRP_CHU_P_60_90_PLUS_ANS/GRP_CHU_TESTED_60_90_PLUS_ANS,
           GRP_CHU_FRACP_TOUS_AGES = CHU_FRACP_TOUS_AGES) %>%
    select(-c(starts_with("GIRONDE_TESTED_"), starts_with("GIRONDE_P_"), starts_with("GIRONDE_FRACP_"),
              starts_with("CHU_TESTED_"), starts_with("CHU_P_"), starts_with("CHU_FRACP_")))
  return(result)
}
